const EMPTY_LENGTH = 0;
const NOT_FOUND_INDEX = -1;
const MIN_INDEX = 0;
const START_INDEX = 0;
const INDEX_OFFSET = 1;
const LAST_INDEX_OFFSET = 1;
const FALLBACK_DEFER_EXECUTION_MS = 0;
const FOCUS_DELAY_MS = 10;

const KNOWLEDGE_TREE_ITEM_CONFIG = {
	BASE_PADDING: 10,
	DEFAULT_LEVEL: 0,
	LEVEL_INCREMENT: 1,
	LEVEL_MULTIPLIER: 16,
	TAB_INDEX_FOCUSABLE: 0,
	TAB_INDEX_UNFOCUSABLE: -1,
} as const;

export {
	EMPTY_LENGTH,
	FALLBACK_DEFER_EXECUTION_MS,
	FOCUS_DELAY_MS,
	INDEX_OFFSET,
	KNOWLEDGE_TREE_ITEM_CONFIG,
	LAST_INDEX_OFFSET,
	MIN_INDEX,
	NOT_FOUND_INDEX,
	START_INDEX,
};
