const HeadingDetection = {
	FONT_SIZE_RATIO: 1.15,
	FONT_SIZE_ROUNDING: 2,
	MAXIMUM_LENGTH: 100,
	MAXIMUM_REPEATED_PAGES: 2,
	MAXIMUM_TEXT_HEADING_LENGTH: 80,
	MINIMUM_HEADINGS: 2,
	SECTION_LEVEL_COUNT: 2,
} as const;

const MINIMUM_PREAMBLE_LENGTH = 200;
const HEADING_TRAILING_PUNCTUATION = /[.,;]$/u;
const HEADING_LETTER = /\p{L}/u;
const MARKDOWN_HEADING = /^(#{1,6})\s+(\S.*)$/u;
const NUMBERED_HEADING = /^(\d+(?:\.\d+)*)\.?\s+\p{Lu}/u;
const NUMBER_SEPARATOR = ".";

export {
	HEADING_LETTER,
	HEADING_TRAILING_PUNCTUATION,
	HeadingDetection,
	MARKDOWN_HEADING,
	MINIMUM_PREAMBLE_LENGTH,
	NUMBER_SEPARATOR,
	NUMBERED_HEADING,
};
