const MILLISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;
const MINUTE_IN_MILLISECONDS = SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;
const SWEEP_INTERVAL_MINUTES = 5;
const STALE_AFTER_MINUTES = 30;

const ProcessingSweep = {
	INTERVAL_MS: SWEEP_INTERVAL_MINUTES * MINUTE_IN_MILLISECONDS,
	STALE_AFTER_MS: STALE_AFTER_MINUTES * MINUTE_IN_MILLISECONDS,
} as const;

export { ProcessingSweep };
