const MAXIMUM_BODY_LIMIT_IN_MEGABYTES = 50;
const BYTES_IN_KILOBYTE = 1024;

const SERVER_BODY_LIMIT_IN_BYTES =
	MAXIMUM_BODY_LIMIT_IN_MEGABYTES * BYTES_IN_KILOBYTE * BYTES_IN_KILOBYTE;

export { SERVER_BODY_LIMIT_IN_BYTES };
