const UserValidationRule = {
	EMAIL_MAXIMUM_LENGTH: 255,
	EMAIL_MINIMUM_LENGTH: 1,
	NAME_MAXIMUM_LENGTH: 255,
	NAME_MINIMUM_LENGTH: 1,
	PASSWORD_MAXIMUM_LENGTH: 255,
	PASSWORD_MINIMUM_LENGTH: 8,
} as const;

export { UserValidationRule };
