const UserValidationRule = {
	EMAIL_MINIMUM_LENGTH: 1,
	NAME_MAXIMUM_LENGTH: 50,
	NAME_MINIMUM_LENGTH: 1,
	PASSWORD_MAXIMUM_LENGTH: 32,
	PASSWORD_MINIMUM_LENGTH: 8,
} as const;

export { UserValidationRule };
