const ADD_KNOWLEDGE_ICON_SIZE = 16;
const ADD_KNOWLEDGE_LABEL = "Add Knowledge";
const APP_SIDEBAR_ID = "app-sidebar";
const BACK_CONTROL_ICON_SIZE = 12;
const BACK_TO_PROJECTS_LABEL = "Back to projects";
const COLLAPSE_SIDEBAR_LABEL = "Collapse sidebar";
const EXPANDED_NAV_ITEM_CLASS = "h-auto w-full justify-start px-3 py-2.5";
const EXPAND_SIDEBAR_LABEL = "Expand sidebar";
const MOBILE_NAV_ICON_SIZE = 16;
const PROJECT_ICON_SIZE = 18;
const RAIL_NAV_ITEM_CLASS = "h-8.5 w-8.5 justify-center p-0";
const SIDEBAR_COLLAPSED_STORAGE_KEY = "knowledgeprism.sidebar-collapsed";
const SIDEBAR_COLLAPSED_STORAGE_VALUE = "true";
const SIDEBAR_EXPANDED_MIN_WIDTH_PX = 1024;
const SIDEBAR_FOCUS_DELAY_MS = 10;
const SIDEBAR_RAIL_MIN_WIDTH_PX = 768;

const SIDEBAR_EXPANDED_MEDIA_QUERY =
	`(min-width: ${String(SIDEBAR_EXPANDED_MIN_WIDTH_PX)}px)` as const;
const SIDEBAR_RAIL_MEDIA_QUERY =
	`(min-width: ${String(SIDEBAR_RAIL_MIN_WIDTH_PX)}px)` as const;

export {
	ADD_KNOWLEDGE_ICON_SIZE,
	ADD_KNOWLEDGE_LABEL,
	APP_SIDEBAR_ID,
	BACK_CONTROL_ICON_SIZE,
	BACK_TO_PROJECTS_LABEL,
	COLLAPSE_SIDEBAR_LABEL,
	EXPAND_SIDEBAR_LABEL,
	EXPANDED_NAV_ITEM_CLASS,
	MOBILE_NAV_ICON_SIZE,
	PROJECT_ICON_SIZE,
	RAIL_NAV_ITEM_CLASS,
	SIDEBAR_COLLAPSED_STORAGE_KEY,
	SIDEBAR_COLLAPSED_STORAGE_VALUE,
	SIDEBAR_EXPANDED_MEDIA_QUERY,
	SIDEBAR_FOCUS_DELAY_MS,
	SIDEBAR_RAIL_MEDIA_QUERY,
};
