const KnowledgeValidationRule = {
	CONTENT_JSON_MINIMUM_ITEMS: 1,
	DOCUMENT_MAXIMUM_DEPTH: 3,
	POSITION_MAXIMUM: 100_000,
	POSITION_MINIMUM: 0,
	QUERY_MAXIMUM_LENGTH: 100,
	SEARCH_RESULTS_MAXIMUM_COUNT: 50,
	TITLE_MAXIMUM_LENGTH: 255,
	TITLE_MINIMUM_LENGTH: 1,
} as const;

export { KnowledgeValidationRule };
