import { type AskPrismResponseDto } from "@knowledgeprism/types";

// TODO: Replace this with the real ProjectAccessContext exported from project.service.ts when PR #118 is merged
type ProjectAccessContext = {
	organisationId: number;
	userId: number;
};

class AskPrismService {
	// TODO: Inject ProjectService when PR #118 is merged
	public constructor() {}

	/**
	 * Temporary mock of ProjectService.assertProjectAccess
	 * TODO: Replace with `await this.projectService.assertProjectAccess(projectId, context);`
	 */
	private async assertProjectAccess(
		projectId: number,
		context: ProjectAccessContext,
	): Promise<void> {
		// Mock implementation: always allows access for now to unblock frontend
		return Promise.resolve();
	}

	public async generateAnswer(
		projectId: number,
		question: string,
		context: ProjectAccessContext,
	): Promise<AskPrismResponseDto> {
		await this.assertProjectAccess(projectId, context);

		// Simulate AI Processing Delay
		await new Promise((resolve) => {
			setTimeout(resolve, 1500);
		});

		// MVP "Not Found" condition simulation (e.g. asking about "pizza" returns empty)
		if (question.toLowerCase().includes("pizza")) {
			return {
				answer: "Not found in the project's knowledge base.",
				sources: [],
			};
		}

		// Mock standard response
		return {
			answer: `This is a simulated RAG-grounded answer to your question: "${question}". In a real scenario, this response will be generated by the Claude LLM strictly using chunks retrieved from the pgvector database.`,
			sources: [
				{
					id: 1,
					nodeId: 42,
					sectionTitle: "User Management Guidelines",
					title: "Password Validation Rules",
				},
				{
					id: 2,
					nodeId: 43,
					sectionTitle: "Security Policies",
					title: "Authentication Standards",
				},
			],
		};
	}
}

export { AskPrismService };
