const DocumentStatus = {
	APPROVED: "APPROVED",
	COMPLETED: "COMPLETED",
	EXTRACTED: "EXTRACTED",
	EXTRACTING: "EXTRACTING",
	FAILED: "FAILED",
	INTEGRATING: "INTEGRATING",
	PARSED: "PARSED",
	PROCESSING: "PROCESSING",
	UPLOADED: "UPLOADED",
	VALIDATED: "VALIDATED",
	WAITING_FOR_APPROVAL: "WAITING_FOR_APPROVAL",
	WAITING_FOR_VALIDATION: "WAITING_FOR_VALIDATION",
} as const;

export { DocumentStatus };
