const DocumentValidationRule = {
	FILE_NAME_MAXIMUM_LENGTH: 255,
	FILE_NAME_MINIMUM_LENGTH: 1,
	MAXIMUM_FILE_SIZE_IN_BYTES: 104_857_600,
	MINIMUM_FILE_SIZE_IN_BYTES: 1,
	PROJECT_ID_MAXIMUM_LENGTH: 255,
	PROJECT_ID_MINIMUM_LENGTH: 1,
} as const;

export { DocumentValidationRule };
