import {
	applyIntegrationChanges,
	cancelDocument,
	checkGlossaryConsistency,
	confirmDocumentUpload,
	createDocumentNode,
	fetchDocumentSections,
	fetchExtractionItems,
	fetchIntegrationChanges,
	fetchKnowledgeEntry,
	fetchKnowledgeTree,
	fetchPendingReviewDocuments,
	initializeProjectKnowledgePipeline,
	moveDocumentNode,
	pollDocumentStatus,
	processDocument,
	removeDocumentNode,
	removeKnowledgeSection,
	resumeNextPendingReview,
	retryDocumentProcessing,
	searchKnowledgeEntries,
	submitExtractionReview,
	submitManualText,
	switchActiveDocument,
	untrackDocument,
	updateExtractionItem,
	updateKnowledgeEntry,
} from "./actions.js";
import { actions as sliceActions } from "./knowledge.slice.js";

const allActions = {
	...sliceActions,
	applyIntegrationChanges,
	cancelDocument,
	checkGlossaryConsistency,
	confirmDocumentUpload,
	createDocumentNode,
	fetchDocumentSections,
	fetchExtractionItems,
	fetchIntegrationChanges,
	fetchKnowledgeEntry,
	fetchKnowledgeTree,
	fetchPendingReviewDocuments,
	initializeProjectKnowledgePipeline,
	moveDocumentNode,
	pollDocumentStatus,
	processDocument,
	removeDocumentNode,
	removeKnowledgeSection,
	resumeNextPendingReview,
	retryDocumentProcessing,
	searchKnowledgeEntries,
	submitExtractionReview,
	submitManualText,
	switchActiveDocument,
	untrackDocument,
	updateExtractionItem,
	updateKnowledgeEntry,
};

export { allActions as actions };
export { reducer } from "./knowledge.slice.js";
