name: Deploy Frontend

on:
  push:
    branches: [development]
    paths:
      - 'apps/web/**'
      - 'packages/**'

  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install NodeJS
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build shared packages
        run: npm run build:packages

      - name: Build frontend
        run: npm run build:web

      - name: Deploy to S3
        run: |
          aws s3 sync apps/web/build/ s3://$S3_BUCKET \
            --delete \
            --cache-control max-age=31536000

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
